# Generated by Django 4.0.6 on 2022-07-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexibeetask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=50)),
                ('empname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibeetask.employee_details')),
            ],
        ),
    ]
